/* eslint-disable import/prefer-default-export */
// export { default as Ads } from "./Ads";
export { default as Anchor } from "./Anchor";
export { default as Box } from "./Box";
export { default as Button } from "./Button";
export { default as Counter } from "./Counter";
export { default as Color } from "./Color";
export { default as Form } from "./Form";
export { default as GlobalStyles } from "./GlobalStyles";
export { default as Icons } from "./Icons";
export { default as Image } from "./Image";
export { default as Info } from "./Info";
export { default as Inputs } from "./Inputs";
export { default as Label } from "./Label";
export { default as Placeholder } from "./Placeholder";
export { default as Text } from "./Text";
export { default as Time } from "./Time";
export { default as Title } from "./Title";
export { default as IconDuration } from "./IconDuration";
export { default as Carousel } from "./Carousel";
export { default as Modal } from "./Modal";
export { default as Multicontent } from "./Multicontent";
export { default as ProgressRing } from "./ProgressRing";
export { default as Dots } from "./Dots";
